name: Build
on:
  push:
    branches:
      - main

jobs:
  build-flutter-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "1.8"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.x"
      - name: Install prereqs
        run: sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libgcrypt20-dev
      - name: Prepare
        run: |
          flutter pub get
          flutter pub run build_runner build
      - name: Build apk
        run: flutter build apk
      - name: Build Linux desktop
        run: |
          flutter config --enable-linux-desktop
          flutter build linux
      - uses: actions/upload-artifact@v2
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk
