name: Kanbasu
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-flutter-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.x"
      - run: flutter pub get
      - name: Prepare
        run: |
          cp ./lib/config.example.dart ./lib/config.dart
          flutter pub run build_runner build
      - run: flutter test
  build-and-deploy-flutter-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "1.8"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.x"
      - run: flutter pub get
      - name: Prepare
        run: |
          cp ./lib/config.example.dart ./lib/config.dart
          flutter pub run build_runner build
      - run: flutter build apk
