name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, labeled, unlabeled, synchronize]
  workflow_dispatch:

jobs:
  test-flutter-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check PR label
        if: contains(github.event.pull_request.labels.*.name, 'wip')
        run: exit 1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.x"
      - name: Install dependencies
        run: flutter pub get
      - name: Codegen
        run: flutter pub run build_runner build
      - name: Lint
        run: dart analyze --fatal-infos
      - name: Test
        run: flutter test --coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
