name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-flutter-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.x"
      - name: Prepare
        run: |
          flutter pub get
          flutter pub run build_runner build
        env:
          PUB_HOSTED_URL: https://mirrors.sjtug.sjtu.edu.cn/dart-pub
          FLUTTER_STORAGE_BASE_URL: https://mirrors.sjtug.sjtu.edu.cn
      - run: dart analyze --fatal-infos
      - run: flutter test
